services:
  db:
    image: postgres:15
    container_name: jogadoresdb
    environment:
      POSTGRES_DB: jogadoresdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - "5432:5432"
    network_mode:
        bridge
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
    db_data: